/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack.crs.ui;
import pack.crs.models.*;
import pack.crs.auth.*;
import java.io.*;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import pack.crs.ui.RecoveryPlanWindow;
/**
 *
 * @author Leonardo
 */
public class AcadOfficerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AcadOfficerDashboard.class.getName());
    private User user;
    private LogStampUtility logStamp;
    private AcademicOfficer officer;
    private List<Student> students;

    /**
     * Creates new form AcadOfficerDashboard
     */
    public AcadOfficerDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public AcadOfficerDashboard(User user, LogStampUtility logStamp, List<Student> students) {
        this.user = user;
        this.logStamp = logStamp;
        this.students = students;
        if (user instanceof AcademicOfficer academicOfficer) {
            this.officer = academicOfficer;
        }
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcadOfficerWelcome = new javax.swing.JLabel();
        btnAcadofficerLogout = new javax.swing.JButton();
        checkEligibilityButton = new javax.swing.JButton();
        btnViewReportsActionPerformed = new javax.swing.JButton();
        btnRecoveryPlan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblAcadOfficerWelcome.setText("Welcome, Academic Officer!");

        btnAcadofficerLogout.setText("Logout");
        btnAcadofficerLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcadofficerLogoutActionPerformed(evt);
            }
        });

        checkEligibilityButton.setText("Check Eligibility");
        checkEligibilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEligibilityButtonActionPerformed(evt);
            }
        });

        btnViewReportsActionPerformed.setText("Academic Performance Report");
        btnViewReportsActionPerformed.setToolTipText("");
        btnViewReportsActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportsActionPerformedActionPerformed(evt);
            }
        });

        btnRecoveryPlan.setText("Recovery Plan");
        btnRecoveryPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecoveryPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAcadOfficerWelcome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAcadofficerLogout)
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecoveryPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewReportsActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEligibilityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAcadOfficerWelcome)
                .addGap(28, 28, 28)
                .addComponent(checkEligibilityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewReportsActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecoveryPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAcadofficerLogout)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnViewReportsActionPerformed.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcadofficerLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcadofficerLogoutActionPerformed
    // TODO add your handling code here:
        try {
            logStamp.appendStamp(user.getUserId(), "logout", "0");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to record logout: " + e.getMessage());
        }
        dispose(); // close dashboard
        new LoginWindow().setVisible(true); // reopen login
    }//GEN-LAST:event_btnAcadofficerLogoutActionPerformed
    
    private void checkEligibilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEligibilityButtonActionPerformed
      new EligibilityCheckerWindow(students, officer,this);
    this.setVisible(false);   
    }//GEN-LAST:event_checkEligibilityButtonActionPerformed

    private void btnViewReportsActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportsActionPerformedActionPerformed
        new AcademicReportWindow(students, officer, this);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewReportsActionPerformedActionPerformed

    private void btnRecoveryPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecoveryPlanActionPerformed
        new RecoveryPlanWindow(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRecoveryPlanActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcadofficerLogout;
    private javax.swing.JButton btnRecoveryPlan;
    private javax.swing.JButton btnViewReportsActionPerformed;
    private javax.swing.JButton checkEligibilityButton;
    private javax.swing.JLabel lblAcadOfficerWelcome;
    // End of variables declaration//GEN-END:variables
}
