package pack.crs.ui;

import pack.crs.auth.*;
import pack.crs.models.*;
import java.io.*;
import javax.swing.*;
import java.util.List;
import pack.crs.utils.*;


public class LoginWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginWindow.class.getName());

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblLoginUser = new javax.swing.JLabel();
        lblLoginPass = new javax.swing.JLabel();
        txtLoginUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtLoginPass = new javax.swing.JPasswordField();
        forgotPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblLogin.setText("Login to your account");

        lblLoginUser.setText("Username :");

        lblLoginPass.setText("Password :");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        forgotPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        forgotPassword.setForeground(new java.awt.Color(51, 51, 255));
        forgotPassword.setText("forgot password?");
        forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblLogin))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(forgotPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                            .addComponent(btnLogin))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLoginPass)
                                .addComponent(lblLoginUser))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLoginUser, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(txtLoginPass)))))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forgotPassword)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoginUser)
                            .addComponent(txtLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoginPass)
                            .addComponent(txtLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtLoginUser.getText().trim();
        String password = new String(txtLoginPass.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in both fields.");
            return;
        }

        try {
            UserDAO userDAO = new UserDAO("Resources/users.txt");
            LogStampUtility logger = new LogStampUtility("Resources/logstamps.dat"); // load binary file
            User user = userDAO.authenticate(username, password);

            if (user == null) {
                JOptionPane.showMessageDialog(this, "Invalid username or password.");
                return;
            }

            if (!user.isActive()) {
                JOptionPane.showMessageDialog(this,
                    "This account has been deactivated.\nPlease contact the System Administrator.",
                    "Account Deactivated",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            logger.appendStamp(user.getUserId(), "login", "1");

            // open new frame
            if (user instanceof SystemAdmin) {
                List<Student> students = FileUtils.importStudents(null);
                new SysAdminWelcome(user, logger, students).setVisible(true);
            } else if (user instanceof AcademicOfficer) {
                List<Student> students = FileUtils.importStudents(null);
                // launch acadofficer dashboard
                new AcadOfficerDashboard(user, logger, students).setVisible(true);

                // Load the students and officer

                AcademicOfficer officer = (AcademicOfficer) user;


            }
            this.dispose(); // close login window

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordMouseClicked
        // TODO add your handling code here:
        String username = txtLoginUser.getText().trim();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your username in the username field first.");
            return;
        }

        try {
            UserDAO userDAO = new UserDAO("Resources/users.txt");
            List<User> all = userDAO.loadAllUsers();
            User found = null;
            for (User u : all) {
                if (u.getUsername() != null && u.getUsername().equalsIgnoreCase(username)) {
                    found = u;
                    break;
                }
            }

            if (found == null) {
                JOptionPane.showMessageDialog(this, "Username not found. Please check the username and try again.");
                return;
            }

            if (found.getEmail() == null || found.getEmail().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No email is registered for this account. Contact admin for reset.");
                return;
            }

            //
            // Email part
            //
            int choice = JOptionPane.showConfirmDialog(this,
                    "An email containing your password will be sent to: " + found.getEmail() + "\nProceed?",
                    "Confirm Password Recovery",
                    JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION)
            {
                NotificationService.sendPasswordRecoveryEmail(found);
                JOptionPane.showMessageDialog(this, "A password recovery email has been sent.");
            }

        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error during password recovery: " + ex.getMessage());
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, "Failed to send recovery email: " + ex.getMessage());
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_forgotPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new LoginWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLoginPass;
    private javax.swing.JLabel lblLoginUser;
    private javax.swing.JPasswordField txtLoginPass;
    private javax.swing.JTextField txtLoginUser;
    // End of variables declaration//GEN-END:variables
}
