/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack.crs.ui;
import pack.crs.models.*;
import pack.crs.auth.*;
import java.io.*;
import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author Leonardo
 */
public class SysAdminWelcome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SysAdminWelcome.class.getName());
    private User user;
    private LogStampUtility logStamp;
    private SystemAdmin admin;
    private List<Student> students;
    /**
     * Creates new form SysAdminWelcome
     */
    public SysAdminWelcome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public SysAdminWelcome(User user, LogStampUtility logStamp, List<Student> students) {
        this.user = user;
        this.logStamp = logStamp;
        this.students = students;
        if (user instanceof SystemAdmin systemAdmin) {
            this.admin = (SystemAdmin) user;
        }
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSysAdmWelcome = new javax.swing.JLabel();
        btnSysAdmLogout = new javax.swing.JButton();
        checkEligibilityButton = new javax.swing.JButton();
        btnViewReportsActionPerformed = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblSysAdmWelcome.setText("Welcome, System Administrator!");

        btnSysAdmLogout.setText("Logout");
        btnSysAdmLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysAdmLogoutActionPerformed(evt);
            }
        });

        checkEligibilityButton.setText("Check Eligibility");
        checkEligibilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEligibilityButtonActionPerformed(evt);
            }
        });

        btnViewReportsActionPerformed.setText("Academic Performance Report");
        btnViewReportsActionPerformed.setToolTipText("");
        btnViewReportsActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportsActionPerformedActionPerformed(evt);
            }
        });

        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblSysAdmWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSysAdmLogout)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnManageUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkEligibilityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewReportsActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblSysAdmWelcome)
                .addGap(18, 18, 18)
                .addComponent(btnManageUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkEligibilityButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewReportsActionPerformed)
                .addGap(42, 42, 42)
                .addComponent(btnSysAdmLogout)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSysAdmLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysAdmLogoutActionPerformed
        // TODO add your handling code here:
        try {
            logStamp.appendStamp(user.getUserId(), "logout", "0");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to record logout: " + e.getMessage());
        }
        dispose(); // close dashboard
        new LoginWindow().setVisible(true); // reopen login
    }//GEN-LAST:event_btnSysAdmLogoutActionPerformed

    private void checkEligibilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEligibilityButtonActionPerformed
         try {
            // call the Admin-capable constructor we added
            EligibilityCheckerWindow ce = new EligibilityCheckerWindow(this.students, this.admin, this);
            ce.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Cannot open eligibility page: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
       
    

       
    
    }//GEN-LAST:event_checkEligibilityButtonActionPerformed

    private void btnViewReportsActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportsActionPerformedActionPerformed
        AcademicReportWindow arw = new AcademicReportWindow(this.students, this.admin, this);
        arw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewReportsActionPerformedActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        // TODO add your handling code here:
        SysAdminDashboard dashboard = new SysAdminDashboard(this.admin, this.logStamp, this);
        dashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManageUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SysAdminWelcome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnSysAdmLogout;
    private javax.swing.JButton btnViewReportsActionPerformed;
    private javax.swing.JButton checkEligibilityButton;
    private javax.swing.JLabel lblSysAdmWelcome;
    // End of variables declaration//GEN-END:variables
}
