/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack.crs.ui;

import pack.crs.models.*;
import pack.crs.auth.*;
import pack.crs.utils.*;

import java.io.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.table.TableModel;
import java.awt.FlowLayout;

/**
 *
 * @author Leonardo
 */
public class SysAdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SysAdminDashboard.class.getName());
    private SystemAdmin admin;
    private LogStampUtility logStamp;
    private UserTableModel tableModel;
    private TableRowSorter<UserTableModel> sorter;
    private SysAdminWelcome welcomeScreen;
    private int edit;   //For multiple edits (used in email key)
    
    /**
     * Creates new form SysAdminDashboard
     */
    public SysAdminDashboard(User user, LogStampUtility logStamp, SysAdminWelcome welcomeScreen) {
        this.admin = (SystemAdmin) user;
        this.logStamp = logStamp;
        this.welcomeScreen = welcomeScreen; //as a reference to the back button
        initComponents();
        setLocationRelativeTo(null);
        loadUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSysAdmWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        lblSysAdmWelcome2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        btnViewLoginStamp = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblSysAdmWelcome.setText("Welcome, System Administrator!");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblUsers);

        lblSysAdmWelcome2.setText("Manage Users");

        btnAdd.setText("Add User");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit User");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDeactivate.setText("Deactivate User");
        btnDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateActionPerformed(evt);
            }
        });

        btnViewLoginStamp.setText("View Login History");
        btnViewLoginStamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLoginStampActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setText("Search:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewLoginStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnDeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSysAdmWelcome)
                                .addGap(0, 638, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSysAdmWelcome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblSysAdmWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewLoginStamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSysAdmWelcome2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // load users (read from file then load to jtable)
    private void loadUsers() {
        try {
            List<User> allUsers = admin.getUserDAO().loadAllUsers();
            tableModel = new UserTableModel(allUsers);
            tblUsers.setModel(tableModel);
            sorter = new TableRowSorter<UserTableModel>(tableModel);
            tblUsers.setRowSorter(sorter);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to load users: " + e.getMessage());
        }
    }

    // validate username, email, and password format
    private boolean isPasswordValid(String pwd) { // min. 6 char with digit, max 15
        if (pwd.length() < 6 || pwd.length() > 15) return false;
        
        boolean hasLetter = false, hasDigit = false;
        for (char c : pwd.toCharArray()) {
            if (Character.isLetter(c)) hasLetter = true;
            if (Character.isDigit(c)) hasDigit = true;
        }
        return hasLetter && hasDigit;
    }
   
    private boolean isUsernameValid(String username) { // min 3 char, max 18 char, can include underscore
        if (username.length() < 3 || username.length() > 18) return false;

        for (char c : username.toCharArray()) {
            if (!Character.isLetterOrDigit(c) && c != '_') {
                // invalid character found
                return false;
            }
        }
        return true;
    }
    
    private boolean isEmailValid(String email) {
        if (email == null) return false;
        email = email.trim();

        if (email.isEmpty()) return false;
        if (email.length() > 100) return false;

        // format is no spaces, one '@', at least one dot in domain, tld ≥ 2 letters (support .com, .ru, etc)
        return email.matches("^[^@\\s]+@[^@\\s]+\\.[A-Za-z]{2,}$");
    }

    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        JTextField txtUser = new JTextField();
        JTextField txtPass = new JTextField();
        JTextField txtEmail = new JTextField();   
        JComboBox<String> cbRole = new JComboBox<>(new String[]{"SystemAdmin", "AcademicOfficer"});
        JCheckBox chkActive = new JCheckBox("Active", true);

        Object[] form = {
            "Username:", txtUser,
            "Email:", txtEmail,
            "Password:", txtPass,
            "Role:", cbRole,
            chkActive
        };

        int result = JOptionPane.showConfirmDialog(this, form, "Add User", JOptionPane.OK_CANCEL_OPTION);
        if (result != JOptionPane.OK_OPTION) return;

        String username = txtUser.getText().trim();
        String password = txtPass.getText().trim();
        String email = txtEmail.getText().trim();
        String role = (String) cbRole.getSelectedItem();
        boolean active = chkActive.isSelected();

        if (username.isEmpty() || password.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username, password and/or email cannot be empty.");
            return;
        }
        
        if (!isUsernameValid(username)) {
            JOptionPane.showMessageDialog(this, "Username must be 3–18 characters long (letters, digits, or underscores only).");
            return;
        }


        if (!isPasswordValid(password)) {
            JOptionPane.showMessageDialog(this, "Password must be 6–15 characters long and contain at least one letter and one digit.");
            return;
        }
        
        if (!isEmailValid(email)) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid email (e.g. name@example.com), max 100 characters.");
            return;
        }

        try {
            List<User> existing = admin.getUserDAO().loadAllUsers();
            boolean duplicate = existing.stream().anyMatch(u -> u.getUsername().equalsIgnoreCase(username)); // username duplicate check
            if (duplicate) {
                JOptionPane.showMessageDialog(this, "Username already exists. Please choose an available name.");
                return;
            }

            String newId = admin.getUserDAO().nextUserId();
            
            User newUser;
            if ("SystemAdmin".equalsIgnoreCase(role)) {
                newUser = new SystemAdmin(newId, username, password, active, email);
            } else {
                newUser = new AcademicOfficer(newId, username, password, active, email);
            }
            
            admin.addUser(newUser);
            loadUsers();
            JOptionPane.showMessageDialog(this, "User added successfully.");

            //
            // Email part
            //
            try 
            {
                NotificationService.sendAccountCreatedEmail(newUser, password);
                JOptionPane.showMessageDialog(this, "Account creation email has been sent.");
            } 
            catch (Exception e){}

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error adding user: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = tblUsers.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a user to edit.");
            return;
        }

        User selected = tableModel.getUserAt(row);
        boolean isOwnAccount = selected.getUserId().equals(admin.getUserId());
        
        JTextField txtUser = new JTextField(selected.getUsername());
        JTextField txtPass = new JTextField();
        JComboBox<String> cbRole = new JComboBox<>(new String[]{"SystemAdmin", "AcademicOfficer"});
        cbRole.setSelectedItem(selected.getRole());
        JCheckBox chkActive = new JCheckBox("Active", selected.isActive());
        JTextField txtEmail = new JTextField(selected.getEmail() != null ? selected.getEmail() : "");

        
        // Disable role and active controls if editing own account to prevent lock-out
        if (isOwnAccount) {
            cbRole.setEnabled(false);
            chkActive.setEnabled(false);
        }
        
        Object[] form = {
            "Username:", txtUser,
            "Email:", txtEmail,
            "New Password (leave blank to keep):", txtPass,
            "Role:", cbRole,
            chkActive
        };
        
        if (isOwnAccount) {
            form = new Object[] {
                "Username:", txtUser,
                "Email:", txtEmail,
                "New Password (leave blank to keep):", txtPass,
                "Role:", cbRole,
                chkActive,
                new JLabel(" "),
                new JLabel("Note: You cannot change your own role or active status.")
            };
        }

        int result = JOptionPane.showConfirmDialog(this, form, "Edit User", JOptionPane.OK_CANCEL_OPTION);
        if (result != JOptionPane.OK_OPTION) return;

        String username = txtUser.getText().trim();
        String password = txtPass.getText().trim();
        String email = txtEmail.getText().trim();
        String role = (String) cbRole.getSelectedItem();
        boolean active = chkActive.isSelected();
        
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username cannot be empty.");
            return;
        }
  
        if (!isUsernameValid(username)) {
            JOptionPane.showMessageDialog(this, "Username must be 3–18 characters long (letters, digits, or underscores only).");
            return;
        }
        
        if (!password.isEmpty() && !isPasswordValid(password)) {
            JOptionPane.showMessageDialog(this, "Password must be 6–15 characters long and contain at least one letter and one digit.");
            return;
        }
        
        if (!isEmailValid(email)) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid email (e.g. name@example.com), max 100 characters.");
            return;
        }

        try {
            List<User> existing = admin.getUserDAO().loadAllUsers();
            boolean duplicate = existing.stream()
                    .anyMatch(u -> u.getUsername().equalsIgnoreCase(username)
                            && !u.getUserId().equals(selected.getUserId())); // check for duplicate AND exclude edited username

            if (duplicate) {
                JOptionPane.showMessageDialog(this, "Username already exists. Please choose an available name.");
                return;
            }
            
            selected.setUsername(username);
            selected.setEmail(email);   
            if (!password.isEmpty()) selected.setPassword(password);
            
            // Only update role and active status if not editing own account
            if (!isOwnAccount) {
                selected.setRole(role);
                selected.setActive(active);
            }

            admin.updateUser(selected);
            loadUsers();
            JOptionPane.showMessageDialog(this, "User updated successfully.");

            //
            // Email part
            //
            try 
            {
                edit ++;
                NotificationService.sendAccountUpdatedEmail(selected, edit);
                JOptionPane.showMessageDialog(this, "Account update email has been sent.");
            } 
            catch (Exception e){}

            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error updating user: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
        // TODO add your handling code here:
        int row = tblUsers.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a user to deactivate.");
            return;
        }

        User selected = tableModel.getUserAt(row);
        
        if (selected.getUserId().equals(admin.getUserId())) {
            JOptionPane.showMessageDialog(this,
                "Account is currently active. You cannot deactivate your own account.",
                "Action Not Allowed",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        if (!selected.isActive()) {
            JOptionPane.showMessageDialog(this,
                "This user is already deactivated.",
                "Action Not Allowed",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
                "Deactivate user " + selected.getUsername() + "?",
                "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            admin.removeUser(selected.getUserId());
            loadUsers();
            JOptionPane.showMessageDialog(this, "User deactivated.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error deactivating user: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadUsers();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnViewLoginStampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLoginStampActionPerformed
        // TODO add your handling code here:
        try {
            List<String[]> logs = logStamp.readAllLogs();
            if (logs.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No login/logout records found.");
                return;
            }

            // define columns
            String[] cols = {"Log ID", "User ID", "Action", "Timestamp"};
            DefaultTableModel model = new DefaultTableModel(cols, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // make table read-only
                }
            };

            // to fill rows
            for (String[] row : logs) {
                model.addRow(new Object[]{row[0], row[1], row[2], row[3]});
            }

            JTable table = new JTable(model);
            table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            table.setRowSelectionAllowed(true);
            table.setColumnSelectionAllowed(false);
            table.setAutoCreateRowSorter(true);

            TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
            table.setRowSorter(sorter);

            // Search field
            JTextField txtSearchLog = new JTextField(20);
            JLabel lblSearch = new JLabel("Search:");

            txtSearchLog.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyReleased(java.awt.event.KeyEvent e) {
                    String text = txtSearchLog.getText().trim();
                    sorter.setRowFilter(text.isEmpty() ? null : RowFilter.regexFilter("(?i)" + text));
                }
            });

            JPanel searchPanel = new JPanel(new java.awt.FlowLayout(FlowLayout.LEFT));
            searchPanel.add(lblSearch);
            searchPanel.add(txtSearchLog);

            JScrollPane scrollPane = new JScrollPane(table);
            scrollPane.setPreferredSize(new java.awt.Dimension(700, 300));

            JPanel panel = new JPanel(new java.awt.BorderLayout());
            panel.add(searchPanel, java.awt.BorderLayout.NORTH);
            panel.add(scrollPane, java.awt.BorderLayout.CENTER);

            JOptionPane.showMessageDialog(this, panel,
                    "Login/Logout Records", JOptionPane.PLAIN_MESSAGE);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to read log file: " + e.getMessage());
        }
    }//GEN-LAST:event_btnViewLoginStampActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String text = txtSearch.getText().trim();
        if (sorter != null) {
            if (text.length() == 0) {
                sorter.setRowFilter(null); // show all
            } else {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            }
    }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();              
        welcomeScreen.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private static class UserTableModel extends AbstractTableModel {
        private final String[] cols = {"ID", "Username", "Email", "Role", "Active"};
        private List<User> users;
        public UserTableModel(List<User> users) { this.users = users; }
        public void setUsers(List<User> users) { this.users = users; fireTableDataChanged(); }
        public User getUserAt(int row) { return users.get(row); }

        @Override public int getRowCount() { return users == null ? 0 : users.size(); }
        @Override public int getColumnCount() { return cols.length; }
        @Override public String getColumnName(int c) { return cols[c]; }
        @Override public Object getValueAt(int r, int c) {
            User u = users.get(r);
            return switch (c) {
                case 0 -> u.getUserId();
                case 1 -> u.getUsername();
                case 2 -> u.getEmail();
                case 3 -> u.getRole();
                case 4 -> u.isActive() ? "Yes" : "No";
                default -> "";
            };
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewLoginStamp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSysAdmWelcome;
    private javax.swing.JLabel lblSysAdmWelcome2;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
